### ISSUE TITLE
TVEnricher gives back social media links that are really not relevant

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#21]
Neither TKK nor RBB want to have social media enrichments (unless, perhaps, if they come from white list channels)

**Comment by rtroncy** [comment]
I'm tempted to close this non-issue if no evidences are given that this is actually the case, providing that adequate calls are being made to the service.

**Comment by rtroncy** [comment]
We have carefully checked what TVEnricher is doing. As per the [documentation](http://www.linkedtv.eu/wiki/index.php/Tvenricher), one MUST provide a set of parameters/values when POST-ing a media resource for enrichment:
- If broadcaster = RBB then enrichments come from ['YouTube', 'Arte7','UEP']
- If broadcaster = SV then enrichments come from ['YouTube','UEP','WikimediaCommons', 'Europeana']
  where YouTube corresponds to specific channels as mentioned in the white lists.
  There is no social media returned. This issue is closed.
