### ISSUE TITLE
so will it be possible to query for a specific dimension in the TVEnricher?

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#22]
(Jaap) e.g (tell me if I'm going too far):
query=resourceUri&dimension=relatedFragments
query=amsterdam+fauvism&dimension=SVwhitelist
query=amsterdam+fauvism&dimension=Europeana 

(Lyndon) and that each dimension is clearly defined in terms of which underlying services are called with which configuration. Then we could maybe more quickly identify where there are discrepancies, e.g. your issue with SVwhitelist queries still including social media results

**Comment by rtroncy** [comment]
TVEnricher can work in two modes: enriching a complete media resource OR on-demand enrichments, see also the [documentation](http://www.linkedtv.eu/wiki/index.php/Tvenricher)
1. Enriching a complete media resource:
   - The `broadcaster` parameter enables to select the set of sources that will be used for the enrichment process
   - If `broadcaster = RBB` then enrichments come from ['YouTube', 'Arte7','UEP']
   - If `broadcaster = SV` then enrichments come from ['YouTube','UEP','WikimediaCommons', 'Europeana']
2. Enriching on-demand:
   - Two additional parameters MUST be specified
   - The `q` parameter to specify the query terms
   - The `strategy` parameter which has for values [combined, freshMedia, Europeana, RBB, SV]

There might be one more possible value when TV2Lucene will be fully integrated. We call the parameter strategy rather than dimension because dimension meant something slightly different when we discussed this with CWI, in a nutshell, something much more specific and closed to end-user requirements (e.g. opinion).

I'm closing this issue since you can already to what you want.

**Comment by lyndonnixon** [comment]
I'm not sure this answers the issue. Strategy is an input parameter? e.g. combined doesn't make sense as an enrichment dimension. 

Does the TVenricher response include a dimension field for each enrichment returned (or whatever else you may call it)

Dimensions are not one to one mapped to strategies. For example, while Europeana and TV2Lucene may well return results that all belong in a single dimension for the enrichment organisation in the ET & Player (related art objects, related video chapters) we discuss that TVNewsEnricher ("RBB" in your current strategy, but eventually the RBB strategy should return links in 3 or more different dimensions) would return links in different dimensions (recent news, related news, timeline). 

So permit me to re-open this issue ;)

**Comment by rtroncy** [comment]
I'm not saying that strategy = dimension. I have said that dimension has a slightly different (more specific) meaning when we coined this term after the focus groups experiments made by CWI.
I have stated that you can do what you want with this parameter. So, yes, strategy is an input parameter.

No, [TVEnricher](http://www.linkedtv.eu/wiki/index.php/Tvenricher) does not have such a 'dimension' field and enrichments are not further categorized but I argue that a client knows this already by issue-ing different calls using different values for the 'strategy' parameter. Similarly, [TVNewsEnricher](http://www.linkedtv.eu/wiki/index.php/TVNewsEnricher) has different API calls (/opinion; /othermedia; /timeline; /indepth)?query=xxx

In the short term, I still think that by changing nothing, you got the expected effect.
