### ISSUE TITLE
TVEnricher: SOLR 'dimension'

### ISSUE THREAD

**Issue by jblom** [linkedtv/wp2#31]
The TVEnricher still returns RBB results even though the SV index is specified:

http://linkedtv.eurecom.fr/tvenricher/api/entity/enrichment/Solr?q=amsterdam&index=SV&granularity=Chapter

**Comment by jthomsen** [comment]
to be sure that there are no old artefacts in the index and the index might be the problem I will delete all indexed data and redo indexing rather then just index it above the old data

**Comment by lyndonnixon** [comment]
Besides the issue with not being able to get SV related chapters (I believe this is with @jthomsen )
- the TVEnricher results provide no hints how or why chapters were selected. If I query on multiple terms with or without quotes I still get the same amount of (different) results. 
- can I have a ranking of chapter results by the number of entities matched in the retrieval? e.g. in News I likely query on the three entities found by Named Entity Expander and want to use first those chapters which reference all three, then two...
- if the editor should curate those results in the Editor Tool he/she needs some hints in the enrichment results to make decisions, e.g. the text fragment from the video transcript where the entity occurred.

So can TV2Lucene and TVEnricher as its wrapper return a RANKING and a SNIPPET field with each chapter result?

**Comment by rtroncy** [comment]
@jthomsen Did the re-indexing in Solr provided a fix to the issue mentioned by @jblom. AFAIK, we don't see this in our tests in EURECOM so for me this is an issue for WP5 and not WP2!

@lyndonnixon Please, create different issues if you have different issues, otherwise, it is very hard to track down what we have to do. To reply to your message, we do not aim to develop an indexing algorithm, this was not foreseen in the DoW and would be quite insane at this stage of the project. Having said this, Solr provides some flexibility and it is efficient. We can play with some parameters to some degree and this is what we aim to do. You're saying we are not providing hints on what is retrieved and why this order. An IR system is a black box, and we cannot influence how Solr is ranking results.

Originally, we had favored recall other precision, but since the St Gallen meeting, we have clearly moved to favor precision over recall. Hence, a query with multiple terms should be translated into a logical AND query which is much more constrained. @jluisred can you please check this is actually the case for the version deployed?

**Comment by jluisred** [comment]
A new version of TVEnricher has been published, solving this and other issues:
- The filtering of media fragments given the provider [SV, RBB, UMONS] is now properly working. The issue https://github.com/linkedtv/wp2/issues/31 is consequently closed.
- The query gives now less relative relevance to visual concepts, compare to the textual terms provided. Precision should be higher for top ranked results.
- Apart of the URL of the Media Fragments, TVEnricher is also providing the corresponding instance in the LinkedTV triplestore (linkedtv:Chapter’s and linkedTV:Shot’s, mainly). By using them, you can easily query the API for getting extra metadata which is not explicitly present in TVEnricher’s response. However in some cases those new IDs are missing, because there are still inconsistencies between the Lucene index and the RDF triplestore, I will shortly open an issue about this.
- The Solr ranking scores are exposed. Thanks to this number you can have a little bit better idea about which fragments are more prominent, and maybe use it for deciding which chapters/shots inside the same MediaResource should be chosen when many are provided in the response.
- Temporal dimension: it allows to filter results by date. Two new query parameters are available: startDate and endDate. However, this feature is still UNAVAILABLE on the server side. The Solr index should be rebuild with a new version of TV2Lucene that I’m gonna publish later this morning. I will further document this feature on the Wiki as well.
